In [1]:
print("Hello World")

Hello World


In [1]:
print("Hello I am a Python Programmer")

Hello I am a Python Programmer


In [2]:
print("Hello I am a Python Programmer and I am learning NumPy and I am a good programmer")

Hello I am a Python Programmer and I am learning NumPy and I am a good programmer


In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
np.array(a)

NameError: name 'a' is not defined

In [7]:
print(arr)

[1 2 3 4 5]
